#+title: simplicial
#+startup: content

* simplicial: Simplicial topology in Python                         :PROJECT:

** Release planning

*** Release 0.7.1

**** Coding [3/5]

     - [X] Add type annotations
     - [X] ...and therefore, drop Python2 support
     - [X] Add CI hooks for Github
     - [ ] Add pasting of simplices to improve construction
     - [ ] Change generators to return complex *and* simplex

**** Bugs [0/1]

     - [ ] Deleting a simplex doesn't update the basis, so basisOf() fails
       when called after deleting a 0-simplex


** Sub-projects

*** Optimisations

    Do we need to store information on all the simplices? The top
    simplices in any star imply the existence of all the smaller
    simplices, although not their arrangement and sharing.


*** Sheaves

    Sheaves over complexes would be extremely useful in looking at
    sensor systems (and other applications). Should this be part of
    the package? -- I think so, as it's a major extension and provides
    a lot of good functionality.

    The issue may be maintaining consistency in the linear maps, since
    it'd be too expensive to check all the restrictions -- although
    perhaps not if it happened as simplices were added, as we then
    only need to check two-step correctness on k simplices. (Still
    potentially a lot of checks for high dimensions.)
